config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  resources :feeds do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :favorites, only: [:create, :destroy]
  end
  resources :favorites, only: [:destroy]

  root to: 'feeds#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # ログイン、アカウント編集後、任意のページに推移させるための記述
  devise_for :users, controllers: {
        sessions: 'users/sessions'
  }
  resources :users, only: [:show]
end

app/models/feed.rb
class Feed < ApplicationRecord

  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 200 }

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites
  has_many :liked_users, through: :favorites, source: :user

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @q = Feed.all.ransack(params[:q])
    @feeds = @q.result(distinct: true).order(id: :desc).page(params[:page])
  end

  def new
    @feed = Feed.new
    # gon.pon = ENV['Rakuten_API_KEY']
  end

  def edit
    # gon.pon = ENV['Rakuten_API_KEY']
  end

  def create
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id
    if @feed.save
      redirect_to feeds_path, notice: "登録が完了しました"
    else
      render 'new'
    end
  end

  def update
    if @feed.update(feed_params)
      redirect_to feeds_path, notice: "登録情報が更新されました"
    else
      render 'edit'
    end
  end

  def show
    @comments = @feed.comments
    @comment = Comment.new
  end

  def destroy
    @feed.destroy
    redirect_to feeds_url, notice: "登録情報が削除されました"
  end

  private
  def set_feed
    @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(
      :title,
      :content,
      :isbn,
      :code
    )
  end

  def correct_user
    @feed = Feed.find(params[:id])
    if current_user.id != @feed.user.id
      redirect_to feeds_path, notice: '作成者ではありません。'
    end
  end
end

app/views/feeds/_form.html.erb
<%= form_for @feed do |f| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "件") %>のエラーがあります。</h2>
      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class = "form-group row">
    <div class="col-sm-12">
    <%= f.label :content, "記事内容" %>
      <%= f.text_field :title, id: "title", placeholder: "タイトル　※1〜50文字", class:"form-control", minlength:1, maxlength:50 %>
    </div><p></p>
    <div class="col-sm-12">
      <%= f.text_area :content, id: "content", placeholder: "本文　※1〜200文字", size: "100x3", class:"form-control", minlength:1, maxlength:200  %>
    </div>
  </div>

  <hr>
  <div class = "form-group row">
    <div class="col-sm-3">
      <%= f.label :search, "ISBN（13桁の数字）などキーワード" %>
      <input type="text" id="search_area">
      <button type="button" id="search_button">検索</button>
    </div>
    <div class="col-sm-9">
      <ul><%= feed.code.try(:html_safe) %></ul>
    </div>
  </div>

  <%= f.text_area :code, id: "code", placeholder: "検索にヒットがあれば、htmlコードがここに出ます", size: "100x2", class:"form-control" %>
  <%= f.hidden_field :isbn, id: "isbn" %>
  <br>
  <%= f.submit '送信する', type: 'button', onclick: 'submit();', class:"btn btn-outline-dark" %>
<% end %>
<br><br>
<br><br>
<br><br>

app/views/feeds/edit.html.erb
<div class="float-right">
<%= link_to t('view.feed_path'), @feed, class: 'btn btn-dark' %>
</div>
<h2>アイテムの編集</h2>
<%= include_gon %>
<%= render 'form', feed: @feed %>

app/views/feeds/index.html.erb
<div class="row">
  <div class="col-12">
  <h2>おすすめ一覧</h2>
  <br>

    <div class="content">
      <%= search_form_for(@q, url:root_path, class: 'mb-5') do |f| %>
        <div class="form-group">
          <%= f.search_field :title_cont, placeholder: "タイトル検索", id: "s_title" %>
          <%= f.submit t('view.search'), class:"btn btn-dark", name:nil %>
        </div>
      <% end %>
    </div>

    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th><%= sort_link(@q, :title, t('view.title')) %></th>
          <th><%= sort_link(@q, :content, t('view.content')) %></th>
          <th><%= sort_link(@q, :updated_at, t('view.updated_at')) %></th>
        </tr>
      </thead>

      <tbody>
        <% @feeds.each do |feed| %>
          <tr>
            <td width="150"><%= image_tag "/icon/#{feed.user_id}.svg", :size =>'30x30' %>　<%= feed.user.name %></td>
            <td width="250"><%= link_to feed.title, feed %></td>
            <td><%= feed.content %></td>
            <td align="right" width="100"><%= time_ago_in_words(feed.updated_at) %>前</td>
            <td align="right" width="100">
            ☆<%= feed.favorites.count %>
            💬<%= feed.comments.count %>
            </td>
            <td align="right" width="120">
            <% if current_user == feed.user %>
            <%= link_to t('view.edit_feed'), edit_feed_path(feed) %>　
            <%= link_to t('view.delete'), feed, method: :delete, data: { confirm: '削除しますか？' } %>
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= paginate @feeds %>
    <br>
    </div>
  </div>
</div>

app/views/feeds/new.html.erb
<h2>アイテムの新規登録</h2>
<%= include_gon %>
<%= render 'form', feed: @feed %>

app/views/feeds/show.html.erb
<div class="float-right">
<% if current_user == @feed.user %>
<%= link_to t('view.edit_feed'), edit_feed_path(@feed), class: 'btn btn-dark' %>
<% end %>
</div>
<p></p>
<p>
  <%= image_tag "/icon/#{@feed.user_id}.svg", :size =>'30x30' %>
  <%= @feed.user.name %><br>
  <h5 class="popover-title">
  <%= @feed.title %></h5>
  <div class="popover-content">
  <%= @feed.content %></div>
  <hr>
  <%= @feed.code.html_safe %><br>
</p>
<hr>
<% if user_signed_in? %>
  <% if current_user != @feed.user && current_user.already_favorited?(@feed) %>
    <%= link_to "☆#{@feed.favorites.count}", feed_favorite_path(@feed), method: :delete %>
    <% elsif current_user != @feed.user %>
    <%= link_to "★#{@feed.favorites.count}", feed_favorites_path(@feed), method: :post %>
    <% else  %>
    ☆<%= @feed.favorites.count %>
    <% end %>
  <% else  %>
  ☆<%= @feed.favorites.count %>
<% end %>

<hr>
<h6>コメント一覧</h6>
<p></p>
  <div id="comments_area">
    <%= render partial: 'comments/index', locals: { comments: @comments, feed_path: @feed_path } %>
  </div>
<p></p>
<% if user_signed_in? %>
  <%= render partial: 'comments/form', locals: { comment: @comment, feed_path: @feed_path } %>
<% end %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>