config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  resources :feeds do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :favorites, only: [:create, :destroy]
  end
  resources :favorites, only: [:destroy]

  root to: 'feeds#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # ログイン、アカウント編集後、任意のページに推移させるための記述
  devise_for :users, controllers: {
        sessions: 'users/sessions'
  }
  resources :users, only: [:show]
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { in: 1..50 }
  
  belongs_to :user
  belongs_to :feed
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_feed

  def create
    @feed = Feed.find(params[:feed_id])
    @comment = @feed.comments.build(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.js { render :errors }
      end
    end
  end

  def show
    @comments = @feed.comments
    @comment = @feed.comment.build
  end

  def edit
    @comment = @feed.comments.find(params[:id])
  end

  def update
    @comment = @feed.comments.find(params[:id])
    
    respond_to do |format|
      if @comment.update(comment_params)
        format.js { render :index }
      else
        format.js { render :errors }
      end
    end
  end

  def destroy
    @comment = @feed.comments.find(params[:id])

    respond_to do |format|
      if current_user.id == @comment.user_id
        @comment.destroy
        format.js { render :index }
      else
        format.html { redirect_to feed_path(@feed), notice: '削除できません' }
      end
    end
  end

  private
  def set_feed
    @feed = Feed.find(params[:feed_id])
  end

  def comment_params
    params.require(:comment).permit(:feed_id, :content)
  end
end

app/views/comments/_edit.html.erb
<div class="container">
<div class="box">
<%= form_with(model: [@feed, @comment]) do |form| %>
  <p id="error-massage"></p>
  <div class="field">
    <%= form.text_area :content, placeholder: "コメント　※1〜50文字", size: "50x2", class: "input", id: "edit_comment" %>
  </div>
  <div class="actions">
    <%= form.submit '編集する', class: "btn btn-dark" %>
  </div>
<% end %>
</div>
</div>

app/views/comments/_errors.html.erb
<div class="errors">
  <% if @comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@comment.errors.count, "件") %>のエラーがあります</h2>
        <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@feed, comment]) do |form| %>
  <div class="field">
    <%= form.text_area :content, placeholder: "コメント　※1〜50文字", size: "50x2", class: "input" %>
  </div>
  <div class="actions">
    <%= form.submit 'コメントする', class: "btn btn-outline-dark" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<table><tr>
<td>
<% comments.each do |comment| %>
  <% if comment.id.present? %>
    <p>
      <%= image_tag "/icon/#{comment.user_id}.svg", :size =>'30x30' %>　
      <%= comment.user.name %>　
      <%= comment.content %>
    <% if user_signed_in? %>
      <% if comment.user_id == current_user.id %>　　　
        <%= link_to '編集', edit_feed_comment_path(comment.feed, comment), remote:true %>
        <%= link_to '削除', [comment.feed, comment], method: :delete, remote: true %>
      <% end %>
    <% end %>
    </p>
  <% end %>
<% end %>
</td>
<td id="comment"></td>
</tr></table>
<p id="error_massage"></p>

app/views/comments/edit.js.erb
$('#comment').html("<%= j(render(partial: '/comments/edit')) %>");

app/views/comments/errors.js.erb
$('#error_massage').html("<%= j(render(partial: '/comments/errors')) %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.feed.comments, feed: @comment.feed }) %>")
$("textarea").val('')