config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  resources :feeds do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :favorites, only: [:create, :destroy]
  end
  resources :favorites, only: [:destroy]

  root to: 'feeds#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # ログイン、アカウント編集後、任意のページに推移させるための記述
  devise_for :users, controllers: {
        sessions: 'users/sessions'
  }
  resources :users, only: [:show]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iHub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p></p>　
    <%= link_to image_tag("/logo.png", :size =>'80x40'),feeds_path %>　
    <%= link_to t('view.feeds'), feeds_path, class: 'btn btn-danger' %>
    <% if user_signed_in? %>　
      <%= link_to t('view.new_feed'), new_feed_path, class: 'btn btn-success' %>
      <div class="float-right">
        <%= link_to t('view.user_path'), user_path(current_user.id), class: 'btn btn-info' %>　
        <%= link_to t('view.destroy_user_session'), destroy_user_session_path, method: :delete %>　　
      </div>
      <% else %>　
        <%= link_to t('view.new_user_registration'), new_user_registration_path, class: 'btn btn-info' %>　
        <%= link_to t('view.new_user_session'), new_user_session_path %>　　
    <% end %>

    <hr>
    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>